tab_spaces = 4
hard_tabs = true
max_width = 75
fn_args_layout = "Compressed"
use_field_init_shorthand = false
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
match_block_trailing_comma = true
